import { CurrencyDetails } from '../../models';

const fiatCurrencies = [
  new CurrencyDetails('usd', 'United States Dollar'),
  new CurrencyDetails('aed', 'United Emirates Dirham'),
  new CurrencyDetails('ars', 'Argentine Peso'),
  new CurrencyDetails('aud', 'Australian Dollar'),
  new CurrencyDetails('bdt', 'Bangladeshi Taka'),
  new CurrencyDetails('bhd', 'Bahraini Dinar'),
  new CurrencyDetails('bmd', 'Bermudian Dollar'),
  new CurrencyDetails('brl', 'Brazil Real'),
  new CurrencyDetails('cad', 'Canadian Dollar'),
  new CurrencyDetails('chf', 'Swiss Franc'),
  new CurrencyDetails('clp', 'Chilean Peso'),
  new CurrencyDetails('cny', 'Chinese Yuan'),
  new CurrencyDetails('czk', 'Czech Koruna'),
  new CurrencyDetails('dkk', 'Danish Krone'),
  new CurrencyDetails('eur', 'Euro'),
  new CurrencyDetails('gbp', 'British Pound Sterling'),
  new CurrencyDetails('hkd', 'Honk Kong Dollar'),
  new CurrencyDetails('huf', 'Hungarian Forint'),
  new CurrencyDetails('idr', 'indonesian Rupiah'),
  new CurrencyDetails('ils', 'Israeli New Shekel'),
  new CurrencyDetails('inr', 'Indian Rupee'),
  new CurrencyDetails('jpy', 'Japanese Yen'),
  new CurrencyDetails('krw', 'South Korean Won'),
  new CurrencyDetails('kwd', 'Kuwaiti Dinar'),
  new CurrencyDetails('lkr', 'Sri Lanka Rupee'),
  new CurrencyDetails('mmk', 'Burmese Kyat'),
  new CurrencyDetails('mxn', 'Mexican Peso'),
  new CurrencyDetails('myr', 'Malaysian Ringgit'),
  new CurrencyDetails('ngn', 'Nigerian Naira'),
  new CurrencyDetails('nok', 'Norwegian Krone'),
  new CurrencyDetails('nzd', 'New Zealand Dollar'),
  new CurrencyDetails('php', 'Philippine Peso'),
  new CurrencyDetails('pkr', 'Pakistani Rupee'),
  new CurrencyDetails('pln', ' Polish Zloty'),
  new CurrencyDetails('rub', 'Russian Ruble'),
  new CurrencyDetails('sar', 'Saudi Riyal'),
  new CurrencyDetails('sek', 'Swedish Krona'),
  new CurrencyDetails('sgd', 'Singapore Dollar'),
  new CurrencyDetails('thb', 'Thai Baht'),
  new CurrencyDetails('try', 'Turkish Lira'),
  new CurrencyDetails('twd', 'New Taiwan Dollar'),
  new CurrencyDetails('uah', 'Ukrainian Hryvnia'),
  new CurrencyDetails('vef', 'Venezuelan Bolivar Fuerte'),
  new CurrencyDetails('vnd', 'Vietnamese Dong'),
  new CurrencyDetails('zar', 'South African Rand'),
  new CurrencyDetails('xdr', 'IMF Special Drawing Rights'),
  new CurrencyDetails('xag', 'Silver - Troy Ounce'),
  new CurrencyDetails('xau', 'Gold - Troy Ounce'),
];

export default fiatCurrencies;
