export const COINS_REQUEST = 'COINS_REQUEST';
export const COINS_SUCCESS = 'COINS_SUCCESS';
export const COINS_ERROR = 'COINS_ERROR';
export const COINS_NEXT_PAGE_REQUEST = 'COINS_NEXT_PAGE_REQUEST';
export const COINS_NEXT_PAGE_SUCCESS = 'COINS_NEXT_PAGE_SUCCESS';
export const COINS_NEXT_PAGE_ERROR = 'COINS_NEXT_PAGE_ERROR';

export const FAVORITE_COINS_REQUEST = 'FAVORITE_COINS_REQUEST';
export const FAVORITE_COINS_SUCCESS = 'FAVORITE_COINS_SUCCESS';
export const FAVORITE_COINS_ERROR = 'FAVORITE_COINS_ERROR';

export const EXCHANGES_REQUEST = 'EXCHANGES_REQUEST';
export const EXCHANGES_SUCCESS = 'EXCHANGES_SUCCESS';
export const EXCHANGES_ERROR = 'EXCHANGES_ERROR';
export const EXCHANGES_NEXT_PAGE_REQUEST = 'EXCHANGES_NEXT_PAGE_REQUEST';
export const EXCHANGES_NEXT_PAGE_SUCCESS = 'EXCHANGES_NEXT_PAGE_SUCCESS';
export const EXCHANGES_NEXT_PAGE_ERROR = 'EXCHANGES_NEXT_PAGE_ERROR';

export const BTC_EXCHANGE_RATES_REQUEST = 'BTC_EXCHANGE_RATES_REQUEST';
export const BTC_EXCHANGE_RATES_SUCCESS = 'BTC_EXCHANGE_RATES_SUCCESS';
export const BTC_EXCHANGE_RATES_ERROR = 'BTC_EXCHANGE_RATES_REQUEST';

export const COIN_CHART_REQUEST = 'COIN_CHART_REQUEST';
export const COIN_CHART_SUCCESS = 'COIN_CHART_SUCCESS';
export const COIN_CHART_ERROR = 'COIN_CHART_ERROR';
export const CANDLESTICK_CHART_SUCCESS = 'CANDLESTICK_CHART_SUCCESS';

export const COIN_DETAILS_REQUEST = 'COIN_DETAILS_REQUEST';
export const COIN_DETAILS_SUCCESS = 'COIN_DETAILS_SUCCESS';
export const COIN_DETAILS_ERROR = 'COIN_DETAILS_ERROR';

export const SET_SORTING_OPTION = 'SET_SORTING_OPTION';
export const TOGGLE_FAVORITE_COIN = 'TOGGLE_FAVORITE_COIN';

export const SET_COIN_CHART_INTERVAL = 'SET_COIN_CHART_INTERVAL';
export const SET_COIN_CHART_TYPE = 'SET_COIN_CHART_TYPE';
export const SET_CHART_VARIANT = 'SET_CHART_VARIANT';

export const COIN_MARKETS_REQUEST = 'COIN_MARKETS_REQUEST';
export const COIN_MARKETS_SUCCESS = 'COIN_MARKETS_SUCCESS';
export const COIN_MARKETS_ERROR = 'COIN_MARKETS_ERROR';
export const COIN_MARKETS_NEXT_PAGE_REQUEST = 'COIN_MARKETS_NEXT_PAGE_REQUEST';
export const COIN_MARKETS_NEXT_PAGE_SUCCESS = 'COIN_MARKETS_NEXT_PAGE_SUCCESS';
export const COIN_MARKETS_NEXT_PAGE_ERROR = 'COIN_MARKETS_NEXT_PAGE_ERROR';

export const EXCHANGE_VOLUME_CHART_REQUEST = 'EXCHANGE_VOLUME_CHART_REQUEST';
export const EXCHANGE_VOLUME_CHART_SUCCESS = 'EXCHANGE_VOLUME_CHART_SUCCESS';
export const EXCHANGE_VOLUME_CHART_ERROR = 'EXCHANGE_VOLUME_CHART_ERROR';

export const EXCHANGE_DETAILS_REQUEST = 'EXCHANGE_DETAILS_REQUEST';
export const EXCHANGE_DETAILS_SUCCESS = 'EXCHANGE_DETAILS_SUCCESS';
export const EXCHANGE_DETAILS_ERROR = 'EXCHANGE_DETAILS_ERROR';
