export const COINS_REQUEST = 'COINS_REQUEST';
export const COINS_SUCCESS = 'COINS_SUCCESS';
export const COINS_ERROR = 'COINS_ERROR';
export const COINS_NEXT_PAGE_REQUEST = 'COINS_NEXT_PAGE_REQUEST';
export const COINS_NEXT_PAGE_SUCCESS = 'COINS_NEXT_PAGE_SUCCESS';
export const COINS_NEXT_PAGE_ERROR = 'COINS_NEXT_PAGE_ERROR';
export const FAVORITE_COINS_REQUEST = 'FAVORITE_COINS_REQUEST';
export const FAVORITE_COINS_SUCCESS = 'FAVORITE_COINS_SUCCESS';
export const FAVORITE_COINS_ERROR = 'FAVORITE_COINS_ERROR';

export const SET_SORTING_OPTION = 'SET_SORTING_OPTION';
export const TOGGLE_FAVORITE_COIN = 'TOGGLE_FAVORITE_COIN';
