export const COIN_LIST_REQUEST = 'COIN_LIST_REQUEST';
export const COIN_LIST_SUCCESS = 'COIN_LIST_SUCCESS';
export const COIN_LIST_ERROR = 'COIN_LIST_ERROR';
export const COIN_LIST_LOAD_MORE = 'COIN_LIST_LOAD_MORE';
